import { assertValidOutboxEvent } from "./payload";
import type { OutboxEvent, ProjectionMutation, ProjectionValue } from "./types";

const IDENTIFIER_PATTERN = /^[a-z][a-z0-9_]*$/;

/**
 * Quotes a trusted schema identifier after enforcing a conservative allowlist.
 *
 * @param identifier - Table or column name supplied by source code, never user input.
 * @returns Safely quoted SQLite identifier.
 */
function quoteIdentifier(identifier: string): string {
  if (!IDENTIFIER_PATTERN.test(identifier)) {
    throw new TypeError(`Unsafe D1 identifier: ${identifier}.`);
  }
  return `"${identifier}"`;
}

/**
 * Serializes JSON with deterministic object-key order for projection receipts.
 *
 * @param value - JSON-compatible event payload.
 * @returns Stable JSON string used for SHA-256 hashing.
 */
function stableJson(value: unknown): string {
  if (value === undefined || typeof value === "bigint" || typeof value === "function") {
    throw new TypeError("Outbox payload must be JSON-serializable.");
  }
  if (value === null || typeof value !== "object") {
    return JSON.stringify(value);
  }
  if (Array.isArray(value)) {
    return `[${value.map((item) => stableJson(item)).join(",")}]`;
  }

  const record = value as Record<string, unknown>;
  return `{${Object.keys(record)
    .sort()
    .map((key) => `${JSON.stringify(key)}:${stableJson(record[key])}`)
    .join(",")}}`;
}

/**
 * Produces a lowercase SHA-256 checksum for an outbox payload.
 *
 * @param payload - Canonical event payload.
 * @returns Hex-encoded checksum persisted with the projection receipt.
 */
async function payloadChecksum(payload: unknown): Promise<string> {
  const digest = await crypto.subtle.digest(
    "SHA-256",
    new TextEncoder().encode(stableJson(payload)),
  );
  return [...new Uint8Array(digest)].map((byte) => byte.toString(16).padStart(2, "0")).join("");
}

/**
 * Builds the watermark predicate that suppresses duplicates and stale events.
 *
 * @returns SQL fragment referencing projection_receipts with five bind values.
 */
function watermarkPredicate(): string {
  return `NOT EXISTS (
    SELECT 1 FROM "projection_receipts"
    WHERE "aggregate_type" = ?
      AND "aggregate_id" = ?
      AND "sync_version" >= ?
  )`;
}

/**
 * Compiles one deterministic mutation into a prepared D1 statement.
 *
 * @param database - D1 binding generated by Wrangler.
 * @param event - Canonical outbox event supplying ordering identity.
 * @param mutation - Validated upsert or delete contract from a projector.
 * @returns A prepared, bound D1 statement guarded by the receipt watermark.
 */
function prepareMutation(
  database: D1Database,
  event: OutboxEvent,
  mutation: ProjectionMutation,
): D1PreparedStatement {
  const table = quoteIdentifier(mutation.table);
  const keyColumn = quoteIdentifier(mutation.keyColumn);
  const watermarkValues: ProjectionValue[] = [
    event.aggregateType,
    event.aggregateId,
    event.syncVersion,
  ];

  if (mutation.action === "delete") {
    return database
      .prepare(
        `DELETE FROM ${table}
         WHERE ${keyColumn} = ? AND ${watermarkPredicate()}`,
      )
      .bind(mutation.keyValue, ...watermarkValues);
  }

  const entries = Object.entries(mutation.values);
  if (entries.length === 0) {
    throw new TypeError("D1 upserts require at least one projected value.");
  }
  const columns = [mutation.keyColumn, ...entries.map(([column]) => column)];
  if (!columns.includes("sync_version")) {
    throw new TypeError("D1 upserts must persist sync_version.");
  }

  const quotedColumns = columns.map(quoteIdentifier);
  const updateColumns = columns.filter((column) => column !== mutation.keyColumn);
  const updateClause = updateColumns
    .map((column) => {
      const quoted = quoteIdentifier(column);
      return `${quoted} = excluded.${quoted}`;
    })
    .join(", ");
  const values = [mutation.keyValue, ...entries.map(([, value]) => value)];

  return database
    .prepare(
      `INSERT INTO ${table} (${quotedColumns.join(", ")})
       SELECT ${quotedColumns.map(() => "?").join(", ")}
       WHERE ${watermarkPredicate()}
       ON CONFLICT (${keyColumn}) DO UPDATE SET ${updateClause}
       WHERE excluded."sync_version" > ${table}."sync_version"`,
    )
    .bind(...values, ...watermarkValues);
}

/**
 * Applies public D1 mutations and their receipt atomically through D1 batch().
 */
export class D1ProjectionWriter {
  /**
   * Creates a projection writer.
   *
   * @param database - D1 public read-model binding generated by Wrangler.
   */
  public constructor(private readonly database: D1Database) {}

  /**
   * Applies a versioned event exactly once at the projection boundary.
   *
   * @param event - Canonical outbox event.
   * @param mutations - Deterministic public read-model changes.
   * @returns Whether D1 changed or had already recorded an equal/newer event.
   */
  public async apply(
    event: OutboxEvent,
    mutations: readonly ProjectionMutation[],
  ): Promise<"applied" | "already-applied"> {
    assertValidOutboxEvent(event);
    if (mutations.length === 0) {
      throw new TypeError("An outbox event must produce at least one mutation.");
    }

    const checksum = await payloadChecksum(event.payload);
    const projectionNames = [...new Set(mutations.map(({ projection }) => projection))]
      .sort()
      .join(",");
    const statements = mutations.map((mutation) => prepareMutation(this.database, event, mutation));
    statements.push(
      this.database
        .prepare(
          `INSERT INTO "projection_receipts"
           ("event_id", "projection", "aggregate_type", "aggregate_id", "sync_version", "applied_at", "payload_checksum")
           VALUES (?, ?, ?, ?, ?, ?, ?)
           ON CONFLICT ("event_id") DO NOTHING`,
        )
        .bind(
          event.id,
          projectionNames,
          event.aggregateType,
          event.aggregateId,
          event.syncVersion,
          new Date().toISOString(),
          checksum,
        ),
    );

    // D1 batch is transactional, so projections never commit without their receipt.
    const results = await this.database.batch(statements);
    const receipt = results.at(-1);
    return receipt?.meta.changes === 0 ? "already-applied" : "applied";
  }
}
