import type { EmailFailure, EmailSendReceipt, RenderedTransactionalEmail } from "./types";

const RETRYABLE_CODES = new Set([
  "E_RATE_LIMIT_EXCEEDED",
  "E_DELIVERY_FAILED",
  "E_INTERNAL_SERVER_ERROR",
]);

/**
 * Sends provider-independent messages through a generated Cloudflare Email binding.
 */
export class CloudflareEmailTransport {
  /**
   * Creates a Cloudflare Email Service adapter.
   *
   * @param binding - EMAIL binding generated by Wrangler.
   */
  public constructor(private readonly binding: SendEmail) {}

  /**
   * Sends a rendered transactional message.
   *
   * @param message - Provider-independent transactional email.
   * @returns Provider message ID used for delivery tracking.
   */
  public async send(message: RenderedTransactionalEmail): Promise<EmailSendReceipt> {
    const from =
      message.from.name === undefined
        ? message.from.email
        : { email: message.from.email, name: message.from.name };
    const result = await this.binding.send({
      to: [...(typeof message.to === "string" ? [message.to] : message.to)],
      from,
      subject: message.subject,
      html: message.html,
      text: message.text,
      ...(message.replyTo === undefined ? {} : { replyTo: message.replyTo }),
      ...(message.headers === undefined ? {} : { headers: { ...message.headers } }),
    });

    return {
      provider: "cloudflare_email",
      providerMessageId: result.messageId,
    };
  }
}

/**
 * Converts an unknown provider exception into a retry policy decision.
 *
 * @param error - Exception thrown by the Email Service binding.
 * @returns Stable error code, safe message, and retry classification.
 */
export function classifyEmailFailure(error: unknown): EmailFailure {
  if (error instanceof Error) {
    const code =
      "code" in error && typeof error.code === "string" ? error.code : "EMAIL_PROVIDER_ERROR";
    return {
      code,
      message: error.message,
      retryable: RETRYABLE_CODES.has(code),
    };
  }

  return {
    code: "EMAIL_PROVIDER_ERROR",
    message: "Unknown email provider failure.",
    retryable: false,
  };
}
